// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: relay/llm/cursor/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// repeated FileContent files = 1;
	Messages       []*ChatMessage_UserMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Instructions   *ChatMessage_Instructions  `protobuf:"bytes,4,opt,name=instructions,proto3" json:"instructions,omitempty"`
	ProjectPath    string                     `protobuf:"bytes,5,opt,name=projectPath,proto3" json:"projectPath,omitempty"`
	Model          *ChatMessage_Model         `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	RequestId      string                     `protobuf:"bytes,9,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Summary        string                     `protobuf:"bytes,11,opt,name=summary,proto3" json:"summary,omitempty"`               // 或许是空的，描述会话做了什么事情，但是不是标题 或许可以当作额外的设定来用
	ConversationId string                     `protobuf:"bytes,15,opt,name=conversationId,proto3" json:"conversationId,omitempty"` // 又来一个uuid
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessages() []*ChatMessage_UserMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatMessage) GetInstructions() *ChatMessage_Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *ChatMessage) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *ChatMessage) GetModel() *ChatMessage_Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *ChatMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatMessage) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ChatMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ResMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResMessage) Reset() {
	*x = ResMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMessage) ProtoMessage() {}

func (x *ResMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMessage.ProtoReflect.Descriptor instead.
func (*ResMessage) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{1}
}

func (x *ResMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatMessage_FileContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename  string                            `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content   string                            `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Position  *ChatMessage_FileContent_Position `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Language  string                            `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Range     *ChatMessage_FileContent_Range    `protobuf:"bytes,6,opt,name=range,proto3" json:"range,omitempty"`
	Length    int32                             `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
	Type      int32                             `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	ErrorCode int32                             `protobuf:"varint,11,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *ChatMessage_FileContent) Reset() {
	*x = ChatMessage_FileContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage_FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_FileContent) ProtoMessage() {}

func (x *ChatMessage_FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_FileContent.ProtoReflect.Descriptor instead.
func (*ChatMessage_FileContent) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ChatMessage_FileContent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ChatMessage_FileContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage_FileContent) GetPosition() *ChatMessage_FileContent_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ChatMessage_FileContent) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ChatMessage_FileContent) GetRange() *ChatMessage_FileContent_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *ChatMessage_FileContent) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ChatMessage_FileContent) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChatMessage_FileContent) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type ChatMessage_UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Role      int32  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	MessageId string `protobuf:"bytes,13,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *ChatMessage_UserMessage) Reset() {
	*x = ChatMessage_UserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage_UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_UserMessage) ProtoMessage() {}

func (x *ChatMessage_UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_UserMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage_UserMessage) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ChatMessage_UserMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage_UserMessage) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ChatMessage_UserMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ChatMessage_Instructions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instruction string `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
}

func (x *ChatMessage_Instructions) Reset() {
	*x = ChatMessage_Instructions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage_Instructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_Instructions) ProtoMessage() {}

func (x *ChatMessage_Instructions) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_Instructions.ProtoReflect.Descriptor instead.
func (*ChatMessage_Instructions) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ChatMessage_Instructions) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type ChatMessage_Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Empty string `protobuf:"bytes,4,opt,name=empty,proto3" json:"empty,omitempty"`
}

func (x *ChatMessage_Model) Reset() {
	*x = ChatMessage_Model{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage_Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_Model) ProtoMessage() {}

func (x *ChatMessage_Model) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_Model.ProtoReflect.Descriptor instead.
func (*ChatMessage_Model) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ChatMessage_Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage_Model) GetEmpty() string {
	if x != nil {
		return x.Empty
	}
	return ""
}

type ChatMessage_FileContent_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line   int32 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column int32 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *ChatMessage_FileContent_Position) Reset() {
	*x = ChatMessage_FileContent_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage_FileContent_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_FileContent_Position) ProtoMessage() {}

func (x *ChatMessage_FileContent_Position) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_FileContent_Position.ProtoReflect.Descriptor instead.
func (*ChatMessage_FileContent_Position) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ChatMessage_FileContent_Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ChatMessage_FileContent_Position) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type ChatMessage_FileContent_Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *ChatMessage_FileContent_Position `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *ChatMessage_FileContent_Position `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *ChatMessage_FileContent_Range) Reset() {
	*x = ChatMessage_FileContent_Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_llm_cursor_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage_FileContent_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_FileContent_Range) ProtoMessage() {}

func (x *ChatMessage_FileContent_Range) ProtoReflect() protoreflect.Message {
	mi := &file_relay_llm_cursor_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_FileContent_Range.ProtoReflect.Descriptor instead.
func (*ChatMessage_FileContent_Range) Descriptor() ([]byte, []int) {
	return file_relay_llm_cursor_message_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *ChatMessage_FileContent_Range) GetStart() *ChatMessage_FileContent_Position {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ChatMessage_FileContent_Range) GetEnd() *ChatMessage_FileContent_Position {
	if x != nil {
		return x.End
	}
	return nil
}

var File_relay_llm_cursor_message_proto protoreflect.FileDescriptor

var file_relay_llm_cursor_message_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2f, 0x6c, 0x6c, 0x6d, 0x2f, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x07, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0xe7, 0x03, 0x0a, 0x0b, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x43, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x3a, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x36, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x1a, 0x81, 0x01, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x1a, 0x5a, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x1a, 0x30, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x31, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relay_llm_cursor_message_proto_rawDescOnce sync.Once
	file_relay_llm_cursor_message_proto_rawDescData = file_relay_llm_cursor_message_proto_rawDesc
)

func file_relay_llm_cursor_message_proto_rawDescGZIP() []byte {
	file_relay_llm_cursor_message_proto_rawDescOnce.Do(func() {
		file_relay_llm_cursor_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_relay_llm_cursor_message_proto_rawDescData)
	})
	return file_relay_llm_cursor_message_proto_rawDescData
}

var file_relay_llm_cursor_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_relay_llm_cursor_message_proto_goTypes = []interface{}{
	(*ChatMessage)(nil),                      // 0: proto.ChatMessage
	(*ResMessage)(nil),                       // 1: proto.ResMessage
	(*ChatMessage_FileContent)(nil),          // 2: proto.ChatMessage.FileContent
	(*ChatMessage_UserMessage)(nil),          // 3: proto.ChatMessage.UserMessage
	(*ChatMessage_Instructions)(nil),         // 4: proto.ChatMessage.Instructions
	(*ChatMessage_Model)(nil),                // 5: proto.ChatMessage.Model
	(*ChatMessage_FileContent_Position)(nil), // 6: proto.ChatMessage.FileContent.Position
	(*ChatMessage_FileContent_Range)(nil),    // 7: proto.ChatMessage.FileContent.Range
}
var file_relay_llm_cursor_message_proto_depIdxs = []int32{
	3, // 0: proto.ChatMessage.messages:type_name -> proto.ChatMessage.UserMessage
	4, // 1: proto.ChatMessage.instructions:type_name -> proto.ChatMessage.Instructions
	5, // 2: proto.ChatMessage.model:type_name -> proto.ChatMessage.Model
	6, // 3: proto.ChatMessage.FileContent.position:type_name -> proto.ChatMessage.FileContent.Position
	7, // 4: proto.ChatMessage.FileContent.range:type_name -> proto.ChatMessage.FileContent.Range
	6, // 5: proto.ChatMessage.FileContent.Range.start:type_name -> proto.ChatMessage.FileContent.Position
	6, // 6: proto.ChatMessage.FileContent.Range.end:type_name -> proto.ChatMessage.FileContent.Position
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_relay_llm_cursor_message_proto_init() }
func file_relay_llm_cursor_message_proto_init() {
	if File_relay_llm_cursor_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relay_llm_cursor_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage_FileContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage_UserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage_Instructions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage_Model); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage_FileContent_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_llm_cursor_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage_FileContent_Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relay_llm_cursor_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_llm_cursor_message_proto_goTypes,
		DependencyIndexes: file_relay_llm_cursor_message_proto_depIdxs,
		MessageInfos:      file_relay_llm_cursor_message_proto_msgTypes,
	}.Build()
	File_relay_llm_cursor_message_proto = out.File
	file_relay_llm_cursor_message_proto_rawDesc = nil
	file_relay_llm_cursor_message_proto_goTypes = nil
	file_relay_llm_cursor_message_proto_depIdxs = nil
}
