// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: cursor/message.proto

package cursor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidiAppend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	SessionKey    *BidiAppend_SessionKey `protobuf:"bytes,2,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiAppend) Reset() {
	*x = BidiAppend{}
	mi := &file_cursor_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiAppend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiAppend) ProtoMessage() {}

func (x *BidiAppend) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiAppend.ProtoReflect.Descriptor instead.
func (*BidiAppend) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{0}
}

func (x *BidiAppend) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *BidiAppend) GetSessionKey() *BidiAppend_SessionKey {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

type StreamUnified struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUnified) Reset() {
	*x = StreamUnified{}
	mi := &file_cursor_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUnified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUnified) ProtoMessage() {}

func (x *StreamUnified) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUnified.ProtoReflect.Descriptor instead.
func (*StreamUnified) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{1}
}

func (x *StreamUnified) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *ChatMessage_Content   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_cursor_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetContent() *ChatMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type ResMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResMessage) Reset() {
	*x = ResMessage{}
	mi := &file_cursor_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMessage) ProtoMessage() {}

func (x *ResMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMessage.ProtoReflect.Descriptor instead.
func (*ResMessage) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{3}
}

func (x *ResMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BidiAppend_SessionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiAppend_SessionKey) Reset() {
	*x = BidiAppend_SessionKey{}
	mi := &file_cursor_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiAppend_SessionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiAppend_SessionKey) ProtoMessage() {}

func (x *BidiAppend_SessionKey) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiAppend_SessionKey.ProtoReflect.Descriptor instead.
func (*BidiAppend_SessionKey) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BidiAppend_SessionKey) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChatMessage_Content struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Messages      []*ChatMessage_Content_Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Model         *ChatMessage_Content_Model     `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Uid           string                         `protobuf:"bytes,23,opt,name=uid,proto3" json:"uid,omitempty"`
	Info          *ChatMessage_Content_Info      `protobuf:"bytes,26,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage_Content) Reset() {
	*x = ChatMessage_Content{}
	mi := &file_cursor_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_Content) ProtoMessage() {}

func (x *ChatMessage_Content) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_Content.ProtoReflect.Descriptor instead.
func (*ChatMessage_Content) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ChatMessage_Content) GetMessages() []*ChatMessage_Content_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatMessage_Content) GetModel() *ChatMessage_Content_Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *ChatMessage_Content) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChatMessage_Content) GetInfo() *ChatMessage_Content_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type ChatMessage_Content_Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// uint32 unknown_field2 = 2;
	Uid string `protobuf:"bytes,13,opt,name=uid,proto3" json:"uid,omitempty"`
	// uint32 unknown_field29 = 29;
	Role          uint32 `protobuf:"varint,47,opt,name=role,proto3" json:"role,omitempty"` //string unknown_field51 = 51;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage_Content_Message) Reset() {
	*x = ChatMessage_Content_Message{}
	mi := &file_cursor_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage_Content_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_Content_Message) ProtoMessage() {}

func (x *ChatMessage_Content_Message) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_Content_Message.ProtoReflect.Descriptor instead.
func (*ChatMessage_Content_Message) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ChatMessage_Content_Message) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ChatMessage_Content_Message) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChatMessage_Content_Message) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type ChatMessage_Content_Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage_Content_Model) Reset() {
	*x = ChatMessage_Content_Model{}
	mi := &file_cursor_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage_Content_Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_Content_Model) ProtoMessage() {}

func (x *ChatMessage_Content_Model) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_Content_Model.ProtoReflect.Descriptor instead.
func (*ChatMessage_Content_Model) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{2, 0, 1}
}

func (x *ChatMessage_Content_Model) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChatMessage_Content_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Bash          string                 `protobuf:"bytes,4,opt,name=bash,proto3" json:"bash,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage_Content_Info) Reset() {
	*x = ChatMessage_Content_Info{}
	mi := &file_cursor_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage_Content_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage_Content_Info) ProtoMessage() {}

func (x *ChatMessage_Content_Info) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage_Content_Info.ProtoReflect.Descriptor instead.
func (*ChatMessage_Content_Info) Descriptor() ([]byte, []int) {
	return file_cursor_message_proto_rawDescGZIP(), []int{2, 0, 2}
}

func (x *ChatMessage_Content_Info) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ChatMessage_Content_Info) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ChatMessage_Content_Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ChatMessage_Content_Info) GetBash() string {
	if x != nil {
		return x.Bash
	}
	return ""
}

func (x *ChatMessage_Content_Info) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_cursor_message_proto protoreflect.FileDescriptor

var file_cursor_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x85,
	0x01, 0x0a, 0x0a, 0x42, 0x69, 0x64, 0x69, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x3d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x2e, 0x42, 0x69, 0x64, 0x69, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x2e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b,
	0x65, 0x79, 0x1a, 0x22, 0x0a, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x55, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xe6, 0x03,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x1a, 0x9f, 0x03, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x37, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x1a, 0x45, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x2f, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x1a, 0x1d, 0x0a, 0x05, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x6c, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cursor_message_proto_rawDescOnce sync.Once
	file_cursor_message_proto_rawDescData = file_cursor_message_proto_rawDesc
)

func file_cursor_message_proto_rawDescGZIP() []byte {
	file_cursor_message_proto_rawDescOnce.Do(func() {
		file_cursor_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_cursor_message_proto_rawDescData)
	})
	return file_cursor_message_proto_rawDescData
}

var file_cursor_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cursor_message_proto_goTypes = []any{
	(*BidiAppend)(nil),                  // 0: cursor.BidiAppend
	(*StreamUnified)(nil),               // 1: cursor.StreamUnified
	(*ChatMessage)(nil),                 // 2: cursor.ChatMessage
	(*ResMessage)(nil),                  // 3: cursor.ResMessage
	(*BidiAppend_SessionKey)(nil),       // 4: cursor.BidiAppend.SessionKey
	(*ChatMessage_Content)(nil),         // 5: cursor.ChatMessage.Content
	(*ChatMessage_Content_Message)(nil), // 6: cursor.ChatMessage.Content.Message
	(*ChatMessage_Content_Model)(nil),   // 7: cursor.ChatMessage.Content.Model
	(*ChatMessage_Content_Info)(nil),    // 8: cursor.ChatMessage.Content.Info
}
var file_cursor_message_proto_depIdxs = []int32{
	4, // 0: cursor.BidiAppend.sessionKey:type_name -> cursor.BidiAppend.SessionKey
	5, // 1: cursor.ChatMessage.content:type_name -> cursor.ChatMessage.Content
	6, // 2: cursor.ChatMessage.Content.messages:type_name -> cursor.ChatMessage.Content.Message
	7, // 3: cursor.ChatMessage.Content.model:type_name -> cursor.ChatMessage.Content.Model
	8, // 4: cursor.ChatMessage.Content.info:type_name -> cursor.ChatMessage.Content.Info
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cursor_message_proto_init() }
func file_cursor_message_proto_init() {
	if File_cursor_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cursor_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_message_proto_goTypes,
		DependencyIndexes: file_cursor_message_proto_depIdxs,
		MessageInfos:      file_cursor_message_proto_msgTypes,
	}.Build()
	File_cursor_message_proto = out.File
	file_cursor_message_proto_rawDesc = nil
	file_cursor_message_proto_goTypes = nil
	file_cursor_message_proto_depIdxs = nil
}
